openapi: 3.0.0
info:
  title: Math Operations API
  version: 1.0.0
paths:
  /api/math:
    post:
      summary: Perform a math operation on two numbers
      description: Accepts two numbers and performs an operation like add, subtract, divide, etc.
      parameters:
        - in: header
          name: X-ArithmeticOp-ID
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                x:
                  type: number
                y:
                  type: number
                operation:
                  type: string
                  enum: [add, subtract, multiply, divide]
              required:
                - x
                - y
                - operation
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: number
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
