/*
 * Math Operations API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{

    /// <summary>
    /// Gets or Sets Operation
    /// </summary>
    [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum OperationEnum
    {
        /// <summary>
        /// Enum AddEnum for add
        /// </summary>
        [EnumMember(Value = "add")]
        AddEnum = 0,
        /// <summary>
        /// Enum SubtractEnum for subtract
        /// </summary>
        [EnumMember(Value = "subtract")]
        SubtractEnum = 1,
        /// <summary>
        /// Enum MultiplyEnum for multiply
        /// </summary>
        [EnumMember(Value = "multiply")]
        MultiplyEnum = 2,
        /// <summary>
        /// Enum DivideEnum for divide
        /// </summary>
        [EnumMember(Value = "divide")]
        DivideEnum = 3
    }
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ApiMathBody : IEquatable<ApiMathBody>
    { 
        /// <summary>
        /// Gets or Sets X
        /// </summary>
        [Required]

        [DataMember(Name="x")]
        public decimal X { get; set; }

        /// <summary>
        /// Gets or Sets Y
        /// </summary>
        [Required]

        [DataMember(Name="y")]
        public decimal Y { get; set; }

     

        /// <summary>
        /// Gets or Sets Operation
        /// </summary>
        [Required]

        [DataMember(Name="operation")]
        public OperationEnum? Operation { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ApiMathBody {\n");
            sb.Append("  X: ").Append(X).Append("\n");
            sb.Append("  Y: ").Append(Y).Append("\n");
            sb.Append("  Operation: ").Append(Operation).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ApiMathBody)obj);
        }

        /// <summary>
        /// Returns true if ApiMathBody instances are equal
        /// </summary>
        /// <param name="other">Instance of ApiMathBody to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ApiMathBody other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    X == other.X ||
                    X != null &&
                    X.Equals(other.X)
                ) && 
                (
                    Y == other.Y ||
                    Y != null &&
                    Y.Equals(other.Y)
                ) && 
                (
                    Operation == other.Operation ||
                    Operation != null &&
                    Operation.Equals(other.Operation)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (X != null)
                    hashCode = hashCode * 59 + X.GetHashCode();
                    if (Y != null)
                    hashCode = hashCode * 59 + Y.GetHashCode();
                    if (Operation != null)
                    hashCode = hashCode * 59 + Operation.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ApiMathBody left, ApiMathBody right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ApiMathBody left, ApiMathBody right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
